name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare workspace
      run: mkdir workspace
    - name: Build the WireGuard tools (wg)
      run: |
        cat build-wg-tools.sh | docker run --rm -i -v="$PWD/workspace:/workspace" -w="/workspace" gcc:latest sh
        ls ./workspace/wireguard-tools/src/wg
        ls ./workspace/wireguard-tools/src/wg-quick/linux.bash
    - name: Get version
      id: getver
      run: echo "::set-output name=body::`./workspace/wireguard-tools/src/wg --version | head -n 1 | cut -d ' ' -f 2`"
